from pathlib import Path

p = Path('scripts/kernel-freeze/kernel-budget-calibration-v4.mjs')
s = p.read_text(encoding='utf-8')

# Add validation mode after policy/semantics checks.
old = '''  const policy = readJson(POLICY_PATH);\n  const semantics = readJson(SEMANTICS_PATH);\n  if (policy.correctnessPredicate?.id !== "HISTORICAL_VALIDITY_V1") fail("correctness contract not recovered");\n  if (semantics?.status !== "RECOVERED") fail("correctness execution semantics not recovered");\n\n  const bundle = await buildBundle(out);\n'''
new = '''  const policy = readJson(POLICY_PATH);\n  const semantics = readJson(SEMANTICS_PATH);\n  if (policy.correctnessPredicate?.id !== "HISTORICAL_VALIDITY_V1") fail("correctness contract not recovered");\n  if (semantics?.status !== "RECOVERED") fail("correctness execution semantics not recovered");\n  const budgetCandidateValidation = Boolean(args.validateCandidateBudgets) || String(args.mode ?? "") === "budget-candidate";\n  const candidateValues = budgetCandidateValidation ? (policy.deterministicBudgets?.candidateValues ?? null) : null;\n  if (budgetCandidateValidation) {\n    const required = [\n      "OPTIMIZER_MAX_BEAM_EXPANSIONS",\n      "OPTIMIZER_BEAM_WATCHDOG_MS",\n      "OPTIMIZER_MAX_MASTER_NODES",\n      "OPTIMIZER_MASTER_WATCHDOG_MS",\n      "OPTIMIZER_MAX_RESCUE_ATTEMPTS",\n      "OPTIMIZER_RESCUE_WATCHDOG_MS",\n    ];\n    if (!candidateValues || required.some((key) => !Number.isSafeInteger(Number(candidateValues[key])) || Number(candidateValues[key]) <= 0)) {\n      fail("--validateCandidateBudgets requires six positive integer deterministicBudgets.candidateValues in policy");\n    }\n  }\n\n  const bundle = await buildBundle(out);\n'''
assert old in s, 'policy block not found'
s = s.replace(old, new, 1)

# Use candidate env and skip calibration telemetry probe in validation mode.
old = '''  const hints = readHistoricalTimingHints();\n  const activationHints = readHistoricalBudgetedPathHints();\n  const env = calibrationEnv();\n\n  await ensureTelemetryProbe({ state, hints, bundle, env, timeoutMs, out });\n\n  const ordered = orderCalibration(\n    state.feasible,\n    hints,\n    policy.execution?.knownExtremeTailOrders ?? [],\n    activationHints,\n    calibrationOrder,\n    oneboardScanLimit,\n    calibrationSampleSeed,\n  );\n  const checkpoint = join(out, "calibration-v4.partial.jsonl");\n'''
new = '''  const hints = readHistoricalTimingHints();\n  const activationHints = readHistoricalBudgetedPathHints();\n  const env = calibrationEnv(candidateValues);\n\n  if (!budgetCandidateValidation) {\n    await ensureTelemetryProbe({ state, hints, bundle, env, timeoutMs, out });\n  }\n\n  const baselineCheckpoint = resolve(String(args.baselineCheckpoint ?? join(out, "calibration-v4.partial.jsonl")));\n  const baselineRows = budgetCandidateValidation\n    ? uniqueLatest(readJsonl(baselineCheckpoint).filter((row) => row.pass === true && row.executionBindingId === EXECUTION_BINDING_ID && row.telemetryContractId === TELEMETRY_CONTRACT_ID))\n    : [];\n  const baselineByFile = new Map(baselineRows.map((row) => [row.file, row]));\n  if (budgetCandidateValidation && baselineRows.length === 0) {\n    fail(`budget candidate validation requires budgets-OFF baseline rows: ${baselineCheckpoint}`);\n  }\n\n  const ordered = budgetCandidateValidation\n    ? state.feasible\n        .filter((item) => baselineByFile.has(item.file))\n        .sort((a, b) => Number(baselineByFile.get(a.file)?.wallMs ?? 0) - Number(baselineByFile.get(b.file)?.wallMs ?? 0) || cmp(a.file, b.file))\n    : orderCalibration(\n        state.feasible,\n        hints,\n        policy.execution?.knownExtremeTailOrders ?? [],\n        activationHints,\n        calibrationOrder,\n        oneboardScanLimit,\n        calibrationSampleSeed,\n      );\n  const checkpoint = budgetCandidateValidation\n    ? join(out, "budget-candidate-v1.partial.jsonl")\n    : join(out, "calibration-v4.partial.jsonl");\n'''
assert old in s, 'env/order/checkpoint block not found'
s = s.replace(old, new, 1)

# Extend pass semantics and row metadata.
old = '''    const beamFallbackAccepted = !beamFallback.present || (beamFallback.controlled && beamAccounting.ok);\n    const pass = Boolean(\n      result.ok &&\n      result.validationOk &&\n      !result.cacheHit &&\n      result.pieces === result.expectedPieces &&\n      result.demandMultisetOk &&\n      telemetryWired &&\n      beamAccounting.ok &&\n      beamFallbackAccepted\n    );\n    const row = {\n      phase: "calibration",\n'''
new = '''    const beamFallbackAccepted = !beamFallback.present || (beamFallback.controlled && beamAccounting.ok);\n    const baseline = budgetCandidateValidation ? baselineByFile.get(item.file) : null;\n    const sameBoardCountAsBaseline = budgetCandidateValidation ? Number(result.boards) === Number(baseline?.boards) : true;\n    const watchdogHits = {\n      beam: Number(result.step0?.beam?.watchdogHits ?? 0),\n      master: Number(result.step0?.master?.watchdogHits ?? 0),\n      oneboard: Number(result.step0?.oneboard?.watchdogHits ?? 0),\n    };\n    const zeroWatchdogHits = watchdogHits.beam === 0 && watchdogHits.master === 0 && watchdogHits.oneboard === 0;\n    const pass = Boolean(\n      result.ok &&\n      result.validationOk &&\n      !result.cacheHit &&\n      result.pieces === result.expectedPieces &&\n      result.demandMultisetOk &&\n      telemetryWired &&\n      beamAccounting.ok &&\n      beamFallbackAccepted &&\n      (!budgetCandidateValidation || (sameBoardCountAsBaseline && zeroWatchdogHits))\n    );\n    const row = {\n      phase: budgetCandidateValidation ? "budget-candidate-validation" : "calibration",\n'''
assert old in s, 'pass block not found'
s = s.replace(old, new, 1)

old = '''      calibrationOneboardSelection: "resto-static-area-lb1",\n      staticAreaLowerBound: staticAreaLowerBound(item.case),\n      file: item.file,\n'''
new = '''      calibrationOneboardSelection: "resto-static-area-lb1",\n      budgetCandidateValidation,\n      candidateValues: budgetCandidateValidation ? candidateValues : null,\n      baselineBoardCount: budgetCandidateValidation ? Number(baseline?.boards) : null,\n      sameBoardCountAsBaseline: budgetCandidateValidation ? sameBoardCountAsBaseline : null,\n      watchdogHits: budgetCandidateValidation ? watchdogHits : null,\n      zeroWatchdogHits: budgetCandidateValidation ? zeroWatchdogHits : null,\n      staticAreaLowerBound: staticAreaLowerBound(item.case),\n      file: item.file,\n'''
assert old in s, 'row metadata marker not found'
s = s.replace(old, new, 1)

# Route summaries and failure message by mode.
old = '''    writeCalibrationSummary(checkpoint, state, hints, out);\n    if (!pass) fail(`calibration validity/work-telemetry failed: ${item.file}; beamAccounting=${JSON.stringify(beamAccounting)}; beamFallback=${JSON.stringify(beamFallback)}; stderr=${result.stderrTail ?? ""}`);\n\n    console.log(JSON.stringify({\n      phase: "calibration",\n'''
new = '''    if (budgetCandidateValidation) writeBudgetCandidateSummary(checkpoint, baselineByFile, candidateValues, out);\n    else writeCalibrationSummary(checkpoint, state, hints, out);\n    if (!pass) {\n      const prefix = budgetCandidateValidation ? "budget candidate equivalence failed" : "calibration validity/work-telemetry failed";\n      fail(`${prefix}: ${item.file}; sameBoardCount=${sameBoardCountAsBaseline}; watchdogHits=${JSON.stringify(watchdogHits)}; beamAccounting=${JSON.stringify(beamAccounting)}; beamFallback=${JSON.stringify(beamFallback)}; stderr=${result.stderrTail ?? ""}`);\n    }\n\n    console.log(JSON.stringify({\n      phase: budgetCandidateValidation ? "budget-candidate-validation" : "calibration",\n'''
assert old in s, 'summary/failure block not found'
s = s.replace(old, new, 1)

old = '''  writeCalibrationSummary(checkpoint, state, hints, out);\n}\n'''
new = '''  if (budgetCandidateValidation) writeBudgetCandidateSummary(checkpoint, baselineByFile, candidateValues, out);\n  else writeCalibrationSummary(checkpoint, state, hints, out);\n}\n'''
assert old in s, 'final summary call not found'
s = s.replace(old, new, 1)

# Make calibrationEnv optionally enable exact candidate values.
old = '''function calibrationEnv() {\n  const env = { ...process.env };\n  for (const key of Object.keys(env)) if (key.startsWith("OPTIMIZER_")) delete env[key];\n  env.OPTIMIZER_V10_STAGED_EXPERIMENTAL = "0";\n  env.OPTIMIZER_POST_BASELINE_CHEAP_LB_EXPERIMENTAL = "0";\n  env.OPTIMIZER_STEP0_TELEMETRY = "1";\n  return env;\n}\n'''
new = '''function calibrationEnv(candidateValues = null) {\n  const env = { ...process.env };\n  for (const key of Object.keys(env)) if (key.startsWith("OPTIMIZER_")) delete env[key];\n  env.OPTIMIZER_V10_STAGED_EXPERIMENTAL = "0";\n  env.OPTIMIZER_POST_BASELINE_CHEAP_LB_EXPERIMENTAL = "0";\n  env.OPTIMIZER_STEP0_TELEMETRY = "1";\n  if (candidateValues) {\n    for (const [key, value] of Object.entries(candidateValues)) env[key] = String(value);\n  }\n  return env;\n}\n'''
assert old in s, 'calibrationEnv block not found'
s = s.replace(old, new, 1)

# Add finite candidate summary before historical timing helper.
marker = '''function readHistoricalTimingHints() {\n'''
helper = '''function writeBudgetCandidateSummary(checkpoint, baselineByFile, candidateValues, out) {\n  const rows = uniqueLatest(\n    readJsonl(checkpoint).filter((row) => row.executionBindingId === EXECUTION_BINDING_ID && row.telemetryContractId === TELEMETRY_CONTRACT_ID),\n  );\n  const failures = rows.filter((row) => row.pass !== true);\n  const boardMismatches = rows.filter((row) => row.sameBoardCountAsBaseline !== true);\n  const watchdogFailures = rows.filter((row) => row.zeroWatchdogHits !== true);\n  const completed = rows.filter((row) => row.pass === true).length;\n  const baselineCases = baselineByFile.size;\n  const status = failures.length > 0 ? "FAIL" : completed === baselineCases ? "PASS" : "PARTIAL";\n  writeJson(join(out, "budget-candidate-v1.summary.json"), {\n    schemaVersion: "kernel-v1-budget-candidate-validation-v1",\n    updatedAt: new Date().toISOString(),\n    kernelCandidate: KERNEL_CANDIDATE,\n    executionBindingId: EXECUTION_BINDING_ID,\n    telemetryContractId: TELEMETRY_CONTRACT_ID,\n    status,\n    candidateValues,\n    baselineCases,\n    completedPassCases: completed,\n    observedRows: rows.length,\n    failures: failures.map((row) => ({ file: row.file, boards: row.boards, baselineBoardCount: row.baselineBoardCount, watchdogHits: row.watchdogHits, stderrTail: row.stderrTail ?? null })),\n    boardMismatches: boardMismatches.map((row) => ({ file: row.file, boards: row.boards, baselineBoardCount: row.baselineBoardCount })),\n    watchdogFailures: watchdogFailures.map((row) => ({ file: row.file, watchdogHits: row.watchdogHits })),\n    promotionReady: status === "PASS",\n    promotionRule: "PASS requires every budgets-OFF baseline calibration case to remain valid, preserve exact boardCount, and report zero Beam/Master/OneBoard watchdog hits under the versioned candidate values.",\n  });\n}\n\n'''
assert marker in s, 'readHistoricalTimingHints marker not found'
if 'function writeBudgetCandidateSummary' not in s:
    s = s.replace(marker, helper + marker, 1)

p.write_text(s, encoding='utf-8')
print('patched finite budget candidate validation mode')
